<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\OfflinePayments\Block\Form\Purchaseorder
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $block->escapeHtml($block->getMethodCode()) ?>">
    <div class="admin__field _required">
        <label for="company_name" class="admin__field-label">
            <span><?= $block->escapeHtml(__('Company Name')) ?></span>
        </label>
        <div class="admin__field-control">
            <input type="text" id="company_name" name="payment[company_name]"
                   title="<?= $block->escapeHtml(__("Company Name")) ?>"
                   class="required-entry admin__control-text"
                   value="<?= /* @noEscape */ $block->getInfoData('company_name') ?>"/>
        </div>
    </div>
</fieldset>
<?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
    "display:none",
    'fieldset#payment_form_' . $block->escapeJs($block->getMethodCode())
) ?>