<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var $block \Magento\OfflinePayments\Block\Info\Purchaseorder
 */
?>
<dl class="payment-method purchase order">
    <dt class="title"><?= $block->escapeHtml($block->getMethod()->getTitle()) ?></dt>
    <dd class="content">
        <strong><?= $block->escapeHtml(__('Company Name')) ?></strong>
        <span class="number"><?= "rohit".$block->escapeHtml($block->getInfoData()->getAdditionalInformation('company_name')) ?></span>
    </dd>
</dl>
<!-- $block->getInfo()->getCompanyName() -->
